(function(){
  'use strict';
  var VERSION='2.4.0', STORE='fast_logistics_v240', state={watchId:null,lastPosition:null};
  function el(id){return document.getElementById(id)}
  function esc(v){var d=document.createElement('div');d.textContent=String(v==null?'':v);return d.innerHTML}
  function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
  function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
  function today(){var d=new Date(),p=function(n){return String(n).padStart(2,'0')};return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())}
  function data(){try{return bancoDados||{rotas:[],despesas:[],sequencias:{}}}catch(e){return {rotas:[],despesas:[],sequencias:{}}}}
  function config(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch(e){return {}}}
  function setConfig(p){localStorage.setItem(STORE,JSON.stringify(Object.assign(config(),p)))}
  function save(){try{if(typeof window.salvarStorage==='function')window.salvarStorage();if(typeof window.fastSalvarSemBloquear==='function')window.fastSalvarSemBloquear(120)}catch(e){console.warn(e)}}
  function toast(t,type){if(typeof window.mostrarToast==='function')window.mostrarToast(t,type||'success');else alert(t)}
  function routesToday(){var d=data(),date=(el('dataSequencia')||{}).value||today(),black=new Set((d.rotasExcluidas||[]).map(String));return ((d.sequencias||{})[date]||[]).filter(function(x){return x&&!black.has(String(x.rotaId||x.id))})}
  function linked(item){return (data().rotas||[]).find(function(r){return String(r.id)===String(item.rotaId)})||item}
  function done(item){var r=linked(item),s=norm(r.statusExecucao||r.statusRota||item.status);return s.indexOf('conclu')>=0}
  function pendingPhotos(){var n=0;try{Object.keys(data().sequencias||{}).forEach(function(k){(data().sequencias[k]||[]).forEach(function(i){if(!done(i)&&!(i.fotos||[]).length&&!i.foto)n++})})}catch(e){}return n}
  function modal(title,body){var m=el('fastLogisticsModal');if(!m){m=document.createElement('div');m.id='fastLogisticsModal';m.className='fl-modal';m.innerHTML='<div class="fl-sheet"><div class="fl-sheet-head"><h3 id="flTitle"></h3><button class="fl-x" type="button" aria-label="Fechar">×</button></div><div id="flBody"></div></div>';document.body.appendChild(m);m.querySelector('.fl-x').onclick=function(){m.classList.remove('show')};m.onclick=function(e){if(e.target===m)m.classList.remove('show')}}el('flTitle').textContent=title;el('flBody').innerHTML=body;m.classList.add('show');return m}
  function refresh(){var list=routesToday(),pend=list.filter(function(i){return !done(i)}),late=pend.filter(isLate),noProof=list.filter(function(i){return done(i)&&!linked(i).comprovanteEntrega}),k={flTotal:list.length,flPending:pend.length,flLate:late.length,flProof:noProof.length};Object.keys(k).forEach(function(id){if(el(id))el(id).textContent=k[id]});var alerts=el('flAlerts');if(alerts){var a=[];if(late.length)a.push('<div class="fl-alert"><i class="fa-solid fa-clock"></i>'+late.length+' rota(s) com risco de atraso.</div>');if(noProof.length)a.push('<div class="fl-alert"><i class="fa-solid fa-file-signature"></i>'+noProof.length+' concluída(s) sem comprovante opcional.</div>');var photos=pendingPhotos();if(photos)a.push('<div class="fl-alert"><i class="fa-solid fa-camera"></i>'+photos+' rota(s) aberta(s) ainda sem foto.</div>');alerts.innerHTML=a.join('')||'<div class="fl-alert ok"><i class="fa-solid fa-circle-check"></i>Operação do dia sem alertas críticos.</div>'}}
  function isLate(i){if(done(i))return false;var raw=i.horario||i.horaLimite||i.janelaFim||'';if(!raw)return false;var parts=String(raw).match(/(\d{1,2}):(\d{2})/);if(!parts)return false;var now=new Date(),limit=new Date();limit.setHours(+parts[1],+parts[2],0,0);return now>limit}
  function installHub(){var tab=el('rotasDia');if(!tab||el('fastLogisticsHub'))return;var card=document.createElement('div');card.id='fastLogisticsHub';card.className='card no-print';card.innerHTML='<div class="fl-head"><h3><i class="fa-solid fa-tower-broadcast"></i> Central Operacional</h3><span class="fl-live">AO VIVO</span></div><div class="fl-kpis"><div class="fl-kpi"><span>Rotas do dia</span><strong id="flTotal">0</strong></div><div class="fl-kpi warn"><span>Pendentes</span><strong id="flPending">0</strong></div><div class="fl-kpi danger"><span>Risco de atraso</span><strong id="flLate">0</strong></div><div class="fl-kpi"><span>Sem comprovante</span><strong id="flProof">0</strong></div></div><div class="fl-tools"><button class="fl-tool" onclick="fastLogOtimizar()"><i class="fa-solid fa-wand-magic-sparkles"></i> Otimizar ordem</button><button class="fl-tool" onclick="fastLogMapa()"><i class="fa-solid fa-map-location-dot"></i> Torre no mapa</button><button class="fl-tool" onclick="fastLogSync()"><i class="fa-solid fa-cloud-arrow-up"></i> Sincronização</button><button class="fl-tool" onclick="fastLogGeo()"><i class="fa-solid fa-location-crosshairs"></i> Geolocalização</button><button class="fl-tool" onclick="fastLogTracking()"><i class="fa-solid fa-link"></i> Rastrear cliente</button><button class="fl-tool" onclick="fastLogInteligencia()"><i class="fa-solid fa-chart-line"></i> Previsões e lucro</button></div><div class="fl-alerts" id="flAlerts"></div>';tab.insertBefore(card,tab.firstElementChild);refresh()}
  window.fastLogOtimizar=function(){var d=data(),date=(el('dataSequencia')||{}).value||today(),list=((d.sequencias||{})[date]||[]);if(list.length<2){toast('É necessário ter pelo menos duas rotas no dia.','info');return}var original=list.slice();list.sort(function(a,b){if(done(a)!==done(b))return done(a)?1:-1;var pa=Number(a.prioridade||0),pb=Number(b.prioridade||0);if(pa!==pb)return pb-pa;var ha=String(a.horario||a.horaLimite||'99:99'),hb=String(b.horario||b.horaLimite||'99:99');if(ha!==hb)return ha.localeCompare(hb);var ma=norm(a.motorista),mb=norm(b.motorista);if(ma!==mb)return ma.localeCompare(mb);return norm(a.destino).localeCompare(norm(b.destino),undefined,{numeric:true})});var changed=list.some(function(x,i){return x!==original[i]});save();if(typeof window.renderizarSequencia==='function')window.renderizarSequencia();refresh();toast(changed?'Rotas reorganizadas por status, prioridade, horário, motorista e destino.':'A ordem atual já é a mais eficiente com os dados disponíveis.','success')};
  window.fastLogMapa=function(){var list=routesToday(),rows=list.map(function(i,n){var q=encodeURIComponent(i.destino||i.cliente||i.origem||'');return '<div class="fl-row"><div class="fl-row-top"><span>'+(n+1)+'º '+esc(i.cliente||'Sem cliente')+'</span><span class="fl-badge">'+(done(i)?'CONCLUÍDA':'EM ROTA')+'</span></div><small>'+esc(i.origem||'—')+' → '+esc(i.destino||'—')+'</small><button class="fl-tool" style="margin-top:7px" onclick="window.open(\'https://www.google.com/maps/search/?api=1&query='+q+'\',\'_blank\')"><i class="fa-solid fa-location-arrow"></i>Abrir no mapa</button></div>'}).join('');modal('Torre de Controle',rows?'<div class="fl-list">'+rows+'</div>':'<p>Nenhuma rota carregada para esta data.</p>')};
  async function drivePending(){try{if(typeof window.abrirDBFotos!=='function')return 'indisponível';var db=await window.abrirDBFotos();return await new Promise(function(ok){var t=db.transaction('driveQueue','readonly'),r=t.objectStore('driveQueue').count();r.onsuccess=function(){ok(r.result||0)};r.onerror=function(){ok('?')}})}catch(e){return 'indisponível'}}
  window.fastLogSync=async function(){var pending=await drivePending(),cloud=false;try{cloud=typeof supabaseDisponivel!=='undefined'&&supabaseDisponivel}catch(e){}var online=navigator.onLine,cfg=config(),body='<div class="fl-sync-line"><strong>Internet</strong><span class="fl-badge">'+(online?'CONECTADA':'OFFLINE')+'</span><small>O trabalho local continua mesmo sem rede.</small></div><div class="fl-sync-line"><strong>Supabase</strong><span class="fl-badge">'+(cloud?'SINCRONIZADO':'VERIFICAR')+'</span><small>Rotas, despesas, clientes e exclusões definitivas.</small></div><div class="fl-sync-line"><strong>Google Drive</strong><span class="fl-badge">'+pending+' pendência(s)</span><small>Fila persistente de fotos aguardando envio.</small></div><div class="fl-sync-line"><strong>Última verificação</strong><span>'+esc(cfg.lastSync||'Ainda não verificada')+'</span><small>O sincronismo usa IDs únicos e registros de exclusão para impedir retornos e duplicações.</small></div><div class="fl-actions"><button class="fl-primary" onclick="fastLogSyncNow()"><i class="fa-solid fa-rotate"></i> Sincronizar agora</button></div>';modal('Central de Sincronização',body)};
  window.fastLogSyncNow=async function(){try{if(typeof window.sincronizarAgora==='function')await window.sincronizarAgora();if(typeof window.fastDriveSincronizarPendentes==='function')await window.fastDriveSincronizarPendentes();setConfig({lastSync:new Date().toLocaleString('pt-BR')});toast('Sincronização concluída.');window.fastLogSync()}catch(e){toast('A sincronização ficou na fila e tentará novamente.','error')}};
  window.fastLogGeo=function(){if(!navigator.geolocation){toast('Geolocalização não disponível neste aparelho.','error');return}if(state.watchId!==null){navigator.geolocation.clearWatch(state.watchId);state.watchId=null;toast('Acompanhamento de localização pausado.','info');return}state.watchId=navigator.geolocation.watchPosition(function(p){state.lastPosition={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,at:new Date().toISOString()};setConfig({lastPosition:state.lastPosition});autoArrival(state.lastPosition)},function(){toast('Autorize a localização para usar chegada automática.','error')},{enableHighAccuracy:true,maximumAge:15000,timeout:20000});toast('Localização ativada. Toque novamente para pausar.')};
  function distance(a,b){var R=6371000,p=Math.PI/180,d1=(b.lat-a.lat)*p,d2=(b.lng-a.lng)*p,x=Math.sin(d1/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
  function autoArrival(pos){routesToday().forEach(function(i){var lat=Number(i.lat||i.latitude),lng=Number(i.lng||i.longitude);if(!lat||!lng||done(i))return;if(distance(pos,{lat:lat,lng:lng})<=Number(i.raioChegada||180)&&!i.chegadaEm){i.chegadaEm=new Date().toISOString();var r=linked(i);r.chegadaEm=i.chegadaEm;save();toast('Chegada automática registrada: '+(i.cliente||i.destino));if(typeof window.renderizarSequencia==='function')window.renderizarSequencia()}})}
  window.fastLogEnviarTracking=function(client,date,fallback){if(typeof window.rastEnviarWhatsAppCliente==='function')return window.rastEnviarWhatsAppCliente(client,date);window.open('https://wa.me/?text='+fallback,'_blank')};
  window.fastLogTracking=function(){var date=(el('dataSequencia')||{}).value||today(),list=routesToday().filter(function(i){return !done(i)}),seen={},rows=list.filter(function(i){var k=norm(i.cliente);if(seen[k])return false;seen[k]=1;return true}).map(function(i){var r=linked(i),msg='Acompanhe sua rota FAST%0ACliente: '+encodeURIComponent(i.cliente||'')+'%0ADestino: '+encodeURIComponent(i.destino||'')+'%0AStatus: EM ROTA'+(r.previsaoChegada?'%0APrevisão: '+encodeURIComponent(r.previsaoChegada):'');return '<div class="fl-row"><div class="fl-row-top"><span>'+esc(i.cliente||'Sem cliente')+'</span><span class="fl-badge">EM ROTA</span></div><small>'+esc(i.destino||'Destino não informado')+'</small><button class="fl-tool" style="margin-top:7px" onclick="fastLogEnviarTracking(\''+esc(i.cliente||'').replace(/'/g,"\\'")+'\',\''+date+'\',\''+msg+'\')"><i class="fa-brands fa-whatsapp"></i>Calcular ETA e compartilhar</button></div>'}).join('');modal('Acompanhamento do Cliente',rows?'<div class="fl-list">'+rows+'</div>':'<p>Não há rotas abertas nesta data.</p>')};
  window.fastLogInteligencia=function(){var d=data(),routes=d.rotas||[],expenses=d.despesas||[],revenue=routes.reduce(function(s,r){return s+Number(r.valor||0)},0),cost=expenses.reduce(function(s,x){return s+Number(x.valor||0)},0),profit=revenue-cost,byDay=[0,0,0,0,0,0,0];routes.forEach(function(r){var dt=new Date((r.data||today())+'T12:00:00');if(!isNaN(dt))byDay[dt.getDay()]++});var max=Math.max.apply(null,byDay.concat([1])),labels=['D','S','T','Q','Q','S','S'],bars=byDay.map(function(v,i){return '<div class="fl-bar" style="height:'+Math.max(5,Math.round(v/max*100))+'%"><span>'+labels[i]+'<br>'+v+'</span></div>'}).join(''),avg=routes.length?revenue/routes.length:0,required=avg>0?Math.ceil(cost/avg):0,late=routesToday().filter(isLate).length,body='<div class="fl-kpis"><div class="fl-kpi"><span>Faturamento</span><strong>'+money(revenue)+'</strong></div><div class="fl-kpi danger"><span>Custos</span><strong>'+money(cost)+'</strong></div><div class="fl-kpi"><span>Resultado</span><strong style="color:'+(profit>=0?'#16a34a':'#dc2626')+'">'+money(profit)+'</strong></div><div class="fl-kpi"><span>Ticket médio</span><strong>'+money(avg)+'</strong></div></div><h4>Previsão operacional</h4><p>Para cobrir as despesas atuais são necessárias aproximadamente <strong>'+required+' rotas</strong> no ticket médio registrado. Hoje existem <strong>'+late+' rota(s)</strong> com risco de atraso baseado no horário limite informado.</p><h4>Demanda histórica por dia da semana</h4><div class="fl-chart">'+bars+'</div><p style="margin-top:30px;font-size:11px;color:var(--text-muted,#64748b)">A previsão melhora automaticamente conforme novas rotas, horários e despesas são registrados.</p>';modal('Inteligência, Previsões e Rentabilidade',body)};
  function proofItem(id){var found=null;Object.keys(data().sequencias||{}).some(function(k){return (data().sequencias[k]||[]).some(function(i){if(String(i.id)===String(id)){found=i;return true}return false})});return found}
  window.fastLogComprovante=function(id){var i=proofItem(id);if(!i)return;var r=linked(i),p=r.comprovanteEntrega||{},body='<p>O comprovante é opcional e só será criado quando você salvar este formulário.</p><div class="fl-grid"><div class="fl-field"><label>Nome de quem recebeu</label><input id="flReceiver" value="'+esc(p.recebedor||'')+'"></div><div class="fl-field"><label>Documento ou referência</label><input id="flDocument" value="'+esc(p.documento||'')+'"></div><div class="fl-field full"><label>Observação</label><textarea id="flProofNote">'+esc(p.observacao||'')+'</textarea></div><div class="fl-field full"><label>Assinatura</label><canvas id="flSignature" class="fl-sign"></canvas><button type="button" class="fl-tool" onclick="fastLogLimparAssinatura()">Limpar assinatura</button></div><div class="fl-field full"><label>Foto do comprovante (opcional)</label><input id="flProofPhoto" type="file" accept="image/*" capture="environment"></div></div><div class="fl-actions"><button class="fl-primary" onclick="fastLogSalvarComprovante(\''+esc(id)+'\')"><i class="fa-solid fa-file-circle-check"></i> Salvar comprovante</button></div>';modal('Comprovante de Entrega — '+(i.cliente||i.destino||''),body);setTimeout(signature,50)};
  function signature(){var c=el('flSignature');if(!c)return;var rect=c.getBoundingClientRect(),ratio=window.devicePixelRatio||1;c.width=rect.width*ratio;c.height=rect.height*ratio;var x=c.getContext('2d');x.scale(ratio,ratio);x.strokeStyle='#111827';x.lineWidth=2;x.lineCap='round';var down=false,last=null;function point(e){var q=e.touches?e.touches[0]:e,r=c.getBoundingClientRect();return {x:q.clientX-r.left,y:q.clientY-r.top}}function start(e){down=true;last=point(e);e.preventDefault()}function move(e){if(!down)return;var p=point(e);x.beginPath();x.moveTo(last.x,last.y);x.lineTo(p.x,p.y);x.stroke();last=p;e.preventDefault()}function end(){down=false}c.addEventListener('pointerdown',start);c.addEventListener('pointermove',move);window.addEventListener('pointerup',end);c.addEventListener('touchstart',start,{passive:false});c.addEventListener('touchmove',move,{passive:false});c._ctx=x}
  window.fastLogLimparAssinatura=function(){var c=el('flSignature');if(c)c.getContext('2d').clearRect(0,0,c.width,c.height)};
  function fileData(f){return new Promise(function(ok){if(!f)return ok('');var r=new FileReader();r.onload=function(){ok(r.result||'')};r.onerror=function(){ok('')};r.readAsDataURL(f)})}
  window.fastLogSalvarComprovante=async function(id){var i=proofItem(id);if(!i)return;var r=linked(i),c=el('flSignature'),photo=await fileData((el('flProofPhoto').files||[])[0]),pos=state.lastPosition||config().lastPosition||null;r.comprovanteEntrega={recebedor:el('flReceiver').value.trim(),documento:el('flDocument').value.trim(),observacao:el('flProofNote').value.trim(),assinatura:c?c.toDataURL('image/png'):'',foto:photo,localizacao:pos,criadoEm:new Date().toISOString(),itemId:String(id)};i.comprovanteEntrega=r.comprovanteEntrega;save();el('fastLogisticsModal').classList.remove('show');if(typeof window.renderizarSequencia==='function')window.renderizarSequencia();refresh();toast('Comprovante salvo nesta rota.')};
  function addProofButtons(){document.querySelectorAll('#containerSequencia .seq-item').forEach(function(card){if(card.querySelector('.fl-proof-btn'))return;var id=card.getAttribute('data-item-id'),group=card.querySelector('.seq-group-status')||card.querySelector('.seq-actions');if(!group||!id)return;var i=proofItem(id),r=i?linked(i):{},b=document.createElement('button');b.type='button';b.className='fl-proof-btn';b.innerHTML='<i class="fa-solid fa-file-signature"></i> '+(r.comprovanteEntrega?'Ver comprovante':'Comprovante');b.onclick=function(){window.fastLogComprovante(id)};group.appendChild(b);if(r.comprovanteEntrega){var s=document.createElement('div');s.className='fl-proof-summary';s.innerHTML='<i class="fa-solid fa-circle-check"></i> Comprovante registrado em '+new Date(r.comprovanteEntrega.criadoEm).toLocaleString('pt-BR');var body=card.querySelector('.seq-body');if(body)body.appendChild(s)}})}
  function patchRender(){var old=window.renderizarSequencia;if(typeof old==='function'&&!old.fastLog240){window.renderizarSequencia=function(){var out=old.apply(this,arguments);setTimeout(function(){addProofButtons();refresh()},20);return out};window.renderizarSequencia.fastLog240=true}addProofButtons()}
  function uid(prefix){return prefix+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,9)}
  function migrateIdentity(){var d=data(),changed=false;(d.rotas||[]).forEach(function(r){if(!r.syncUid){r.syncUid=uid('rota');changed=true}if(!r.updatedAt){r.updatedAt=new Date(Number(r.id)||Date.now()).toISOString();changed=true}});(d.despesas||[]).forEach(function(x){if(!x.syncUid){x.syncUid=uid('desp');changed=true}if(!x.updatedAt){x.updatedAt=new Date(Number(x.id)||Date.now()).toISOString();changed=true}});Object.keys(d.sequencias||{}).forEach(function(k){(d.sequencias[k]||[]).forEach(function(i){if(!i.syncUid){i.syncUid=uid('dia');changed=true}})});if(changed)save()}
  function installExpenseRouteLink(){var form=el('formDespesa');if(!form||el('fastExpenseRoute'))return;var actions=form.querySelector('.span-4[style*="display: flex"]')||form.lastElementChild,wrap=document.createElement('div');wrap.className='span-4';wrap.innerHTML='<label><i class="fa-solid fa-route"></i> Vincular a uma rota (opcional):</label><select id="fastExpenseRoute"><option value="">Despesa geral, sem rota específica</option></select>';form.insertBefore(wrap,actions);var select=el('fastExpenseRoute'),routes=(data().rotas||[]).slice().sort(function(a,b){return String(b.data||'').localeCompare(String(a.data||''))}).slice(0,150);routes.forEach(function(r){var o=document.createElement('option');o.value=r.id;o.textContent=(r.data||'Sem data')+' · '+(r.cliente||'Sem cliente')+' · '+(r.destino||'Sem destino');select.appendChild(o)});var old=window.salvarDespesa;if(typeof old==='function'&&!old.fastLog240){window.salvarDespesa=function(e){var routeId=(el('fastExpenseRoute')||{}).value||'',before=(data().despesas||[]).length,out=old.apply(this,arguments),list=data().despesas||[];if(list.length>before){var x=list[list.length-1];x.rotaId=routeId;x.syncUid=x.syncUid||uid('desp');x.updatedAt=new Date().toISOString();save()}return out};window.salvarDespesa.fastLog240=true}}
  function boot(){document.documentElement.setAttribute('data-fast-version',VERSION);var m=document.querySelector('meta[name="fast-app-version"]');if(m)m.content=VERSION;['fastSplashVersion','fastGateVersionNum','fastVersaoLabel'].forEach(function(id){if(el(id))el(id).textContent=VERSION});if(el('navMenuVersao'))el('navMenuVersao').textContent='Versão '+VERSION;migrateIdentity();installHub();installExpenseRouteLink();patchRender();var observer=new MutationObserver(function(){addProofButtons();refresh()});var cont=el('containerSequencia');if(cont)observer.observe(cont,{childList:true,subtree:true});setInterval(refresh,60000);var changes=[{type:'novo',text:'2.4.0 (12/09/2026): Central Operacional reúne rotas pendentes, risco de atraso, comprovantes, mapa, otimização, geolocalização e acompanhamento do cliente.'},{type:'novo',text:'2.4.0: comprovante completo e opcional com recebedor, documento, observação, assinatura, foto, data, hora e localização; nunca abre automaticamente ao concluir.'},{type:'novo',text:'2.4.0: previsões de demanda, risco de atraso, ticket médio e rentabilidade com dados reais do FAST.'},{type:'melhorado',text:'2.4.0: Central de Sincronização apresenta internet, Supabase, fila do Google Drive e última verificação.'},{type:'melhorado',text:'2.4.0: rotas, despesas e itens do dia recebem identificação única de sincronização; despesas podem ser vinculadas diretamente a uma rota.'}];window.fastUltimoModuloNovidades=changes;var c=document.querySelector('meta[name="fast-app-changelog"]');if(c)c.content=JSON.stringify(changes)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(boot,450)});else setTimeout(boot,450)
})();
