(function(){
  try{if(!('bancoDados'in window))Object.defineProperty(window,'bancoDados',{configurable:true,get:function(){return bancoDados}})}catch(e){}
  window.editarMotorista=window.editarMotorista||function(id){return abrirModalEditarMotorista(id)};
  function cls(s){s=String(s||'').toLowerCase();if(/aprov|ativo/.test(s))return'aprovado';if(/neg|bloque/.test(s))return'negado';if(/análise|analise|processo/.test(s))return'analise';return'novo'}
  function escM(v){return typeof escapeHtml==='function'?escapeHtml(String(v==null?'':v)):String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  window.fastMotRenderCadastros=function(){var host=document.getElementById('fastMotCadastroLista');if(!host||!window.bancoDados)return;var list=(bancoDados.motoristas||[]).filter(function(m){return m.origem==='FAST Motorista'||m.aprovacaoStatus});if(!list.length){host.innerHTML='<p style="color:var(--text-muted);font-size:12px">Nenhum cadastro recebido do app Motorista.</p>';return}host.innerHTML=list.slice().sort(function(a,b){return String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||''))}).map(function(m){var c=cls(m.aprovacaoStatus||m.status),docs=Array.isArray(m.documentos)?m.documentos:[];return '<article class="fast-mot-admin-card '+c+'"><div style="display:flex;justify-content:space-between;gap:8px"><b>'+escM(m.nome||'Motorista')+'</b><span class="badge-status">'+escM(m.aprovacaoStatus||m.status||'Cadastro novo')+'</span></div><div class="fast-mot-admin-grid"><div><b>CPF</b>'+escM(m.cpf||'—')+'</div><div><b>CNH / Categoria</b>'+escM((m.cnh||'—')+' / '+(m.cnhCategoria||'—'))+'</div><div><b>Veículo</b>'+escM((m.placa||'—')+' · '+(m.veiculo||'—'))+'</div><div><b>Contato</b>'+escM(m.email||m.telefone||'—')+'</div></div><div class="fast-mot-admin-docs">'+docs.map(function(d){var src=d.url||d.data;return src?'<a href="'+src+'" target="_blank" rel="noopener"><img src="'+src+'" alt="'+escM(d.tipo)+'">'+escM(String(d.tipo||'documento').replaceAll('_',' '))+'</a>':''}).join('')+'</div>'+(m.motivoNegacao?'<p style="color:#dc2626"><b>Motivo:</b> '+escM(m.motivoNegacao)+'</p>':'')+'<div class="fast-mot-admin-actions"><button class="analise" onclick="fastMotStatus('+JSON.stringify(String(m.id))+',\'Em processo de aprovação\')">Analisar</button><button class="aprovar" onclick="fastMotStatus('+JSON.stringify(String(m.id))+',\'Motorista aprovado\')">Aprovar</button><button class="negar" onclick="fastMotNegar('+JSON.stringify(String(m.id))+')">Negar</button><button style="background:#475569" onclick="editarMotorista('+JSON.stringify(String(m.id))+')">Ver cadastro completo</button></div></article>'}).join('')}
  async function avisar(m){try{await fetch(SUPABASE_URL.replace('/rest/v1','')+'/functions/v1/motorista-status-email',{method:'POST',headers:supabaseHeaders(),body:JSON.stringify({email:m.email,nome:m.nome,status:m.aprovacaoStatus,motivo:m.motivoNegacao||''})})}catch(e){console.warn('Aviso por e-mail ficará pendente:',e)}}
  window.fastMotStatus=function(id,status,motivo){var m=(bancoDados.motoristas||[]).find(function(x){return String(x.id)===String(id)});if(!m)return;m.aprovacaoStatus=status;m.status=status==='Motorista aprovado'?'Ativo':status;m.motivoNegacao=motivo||'';m.updatedAt=new Date().toISOString();salvarStorage();if(typeof sincronizarAgora==='function')sincronizarAgora();fastMotRenderCadastros();renderizarMotoristas();avisar(m);mostrarToast(status==='Motorista aprovado'?'Motorista liberado com sucesso.':'Status do cadastro atualizado.','success')}
  window.fastMotNegar=function(id){var motivo=prompt('Informe o motivo da negativa. Ele será mostrado ao motorista:');if(!motivo||!motivo.trim())return;fastMotStatus(id,'Motorista negado',motivo.trim())}
  var old=window.renderizarMotoristas;window.renderizarMotoristas=function(){var out=old&&old.apply(this,arguments);setTimeout(fastMotRenderCadastros,0);return out};addEventListener('DOMContentLoaded',function(){setTimeout(fastMotRenderCadastros,800)});
})();
